config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :products, except: [:destroy, :show]
  namespace :admin do
    resources :users, only: [:index] do
      post :promotion
      delete :demotion
    end
  end

  get "role/upgrade" ,to: "roles#premium"
  root "products#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  validates_presence_of :name, :price, :image
  mount_uploader :image, ImageUploader
end

app/models/role.rb
class Role < ApplicationRecord
  has_many :user_roles, dependent: :destroy
  has_many :users, through: :user_roles, source: :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :user_roles, dependent: :destroy
  has_many :roles, through: :user_roles, source: :role

  def is_admin
    roles.find_by(name: 'admin').present?
  end

  def is_premium
    roles.find_by(name: 'premium').present?
  end
end

app/models/user_role.rb
class UserRole < ApplicationRecord
  belongs_to :user
  belongs_to :role
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin
  before_action :find_user, only: [:promotion, :demotion]

  def index
    @users = User.all.order(created_at: :DESC)
  end

  def promotion
    @user.roles << Role.find_by(name: 'admin')
    flash[:notice] = "#{@user.email} are Admin now!" 
    redirect_back(fallback_location: admin_users_path)
  end

  def demotion
    @user.user_roles.where(role_id: Role.find_by(name: 'admin').id).destroy_all
    flash[:notice] = "#{@user.email} are normal user now!" 
    redirect_back(fallback_location: admin_users_path)
  end

  private

  def find_user
    @user = User.find(params[:user_id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def authenticate_admin
    unless current_user.try(:is_admin)
      flash[:alert] = "Not allow!"
      redirect_to root_path
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_admin, except: [:index]
  before_action :set_product, only: [:edit, :update]

  def index
    @products = Product.all.order(created_at: :DESC).page(params[:page]).per(6)
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.create!(product_params)
    if @product.save
      flash[:notice] = "成功建立 Product"
      redirect_to root_path
    else
      flash[:alert] = @product.errors.full_messages.to_sentence
      redirect_back(fallback_location: new_product_path)
    end
  end

  def update
    if @product.update_attributes(product_params)
      flash[:notice] = "成功更新 Product"
      redirect_to root_path
    else
      flash[:alert] = @product.errors.full_messages.to_sentence
      redirect_back(fallback_location: edit_product_path)
    end
  end

  private

  def product_params
    params.require(:product).permit(:name, :price, :image)
  end

  def set_product
    @product = Product.find(params[:id])
  end
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  before_action :authenticate_user!

  def premium
    if current_user
      if current_user.roles.find_by(name: 'premium').blank?
        current_user.roles << Role.find_by(name: 'premium')
        flash[:notice] = "You are Premium now!" 
        redirect_back(fallback_location: root_path)
      else
        flash[:alert] = "You are Premium alredy, you don't need to upgrade again!" 
        redirect_back(fallback_location: root_path)
      end
    else
      flash[:alert] = "Please Sign In/Up First" 
      redirect_back(fallback_location: root_path)
    end
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/views/admin/users/index.html.erb
<div class="container-fluid">
  <div class="table-responsive">
    <table class="table table-bordered">
      <thead class="thead-light">
        <tr>
          <th scope="col">Email</th>
          <th scope="col">Role</th>
          <th scope="col">Promotion/Demotion</th>
        </tr>
      </thead>
      <tbody>
        <% @users.each do |user| %>
          <tr>
            <td><%= user.email %></td>
            <% if user.is_admin %>
              <td>Admin</td>
            <% else %>
              <td>Normal</td>
            <% end %>
            <td>
              <% if user.is_admin %>
                <%= link_to "Demotion", admin_user_demotion_path(user_id: user.id), method: :delete, class: "btn btn-outline-danger" %>
              <% else %>
                <%= link_to "Promotion", admin_user_promotion_path(user_id: user.id), method: :post, class: "btn btn-outline-primary" %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MemberSystem</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container-fluid" style="padding-right: 0px; padding-left: 0px;">
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <%= link_to "Member System", root_path, class: "navbar-brand" %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <% if current_user %>
              <% if current_user.is_admin %>
                <li class="nav-item">
                  <%= link_to "New Product", new_product_path, class: "nav-link" %>
                </li>
              <% end %>
            <% end %>
          </ul>

          <ul class="navbar-nav">
            <% if current_user %>
              <% if current_user.is_admin && current_user.is_premium %>
                <span class="navbar-text", style="padding: 8px 8px;">
                  <span class="badge badge-info">Admin</span> 
                  <span class="badge badge-warning">Premium</span> 
                  <%= current_user.email %>
                </span>
                <li class="nav-item">
                  <%= link_to "Admin Panel", root_path, class: "nav-link" %>
                </li>
                <li class="nav-item">
                  <%= link_to "Log out", destroy_user_session_path, class: "nav-link", method: :delete %>
                </li>
              <% elsif current_user.is_admin %>
                <span class="navbar-text", style="padding: 8px 8px;">
                  <span class="badge badge-info">Admin</span> <%= current_user.email %>
                </span>
                <li class="nav-item", style="padding: 8px 8px;">
                  <%= link_to "Upgrade to Premium", role_upgrade_path, class: "badge badge-warning" %>
                </li>
                <li class="nav-item">
                  <%= link_to "Admin Panel", admin_users_path, class: "nav-link" %>
                </li>
                <li class="nav-item">
                  <%= link_to "Log out", destroy_user_session_path, class: "nav-link", method: :delete %>
                </li>
              <% elsif current_user.is_premium %>
                <span class="navbar-text">
                  <span class="badge badge-warning">Premium</span> <%= current_user.email %>
                </span>
                <li class="nav-item">
                  <%= link_to "Log out", destroy_user_session_path, class: "nav-link", method: :delete %>
                </li>
              <% else %>
                <span class="navbar-text">
                  <%= current_user.email %>
                </span>  
                <li class="nav-item", style="padding: 8px 8px;">
                  <%= link_to "Upgrade to Premium", role_upgrade_path, class: "badge badge-warning" %>
                </li>
                <li class="nav-item">
                  <%= link_to "Log out", destroy_user_session_path, class: "nav-link", method: :delete %>
                </li>
              <% end %>
            <% else %>
              <li class="nav-item">
                <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to "Log in", new_user_session_path, class: "nav-link" %>
              </li>
            <% end %>
          </ul>
        </div>
      </nav>
    </div>

    <% if notice.present? %>
      <div class="alert alert-success alert-dismissible" role="alert" style="margin-bottom: 0px;">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <p><%= notice %></p>
      </div>
    <% elsif alert.present? %>
      <div class="alert alert-danger alert-dismissible" role="alert" style="margin-bottom: 0px;">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <p><%= alert %></p>
      </div>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/products/edit.html.erb
<div class="container">
  <div class="text-center">
    <h1>Edit Product</h1> 
  </div>
  <br />
  <%= render partial: "shared/product" %>

</div>

app/views/products/index.html.erb
<div class="container text-center", style="margin-top: 70px;">
  <div class="row justify-content-md-center">
    <% @products.each do |prod| %>
      <div class="col-md-auto col-sm-12 mb-4">
        <div class="card" style="width: 18rem;">
          <%= image_tag prod.image_url, width: '300px', height: '250', class: 'card-img-top', alt: 'Card image cap' if prod.image_url %>
          <div class="card-body">
            <h5 class="card-title"><%= prod.name %></h5>
            <% if current_user %>
              <% if current_user.is_premium %>
                <p class="card-text">Price: <%= number_to_currency((prod.price * 0.9)) %></p>
              <% else %>
                <p class="card-text">Price: <%= number_to_currency(prod.price) %></p>
              <% end %>

              <% if current_user.is_admin %>
                <%= link_to "Edit", edit_product_path(prod), class: "btn btn-outline-secondary" %>
              <% end %>
            <% else %>
              <p class="card-text">Price: <%= number_to_currency(prod.price) %></p>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <div class="row justify-content-md-center">
    <%= paginate @products %>
  </div>
</div>

app/views/products/new.html.erb
<div class="container">
  <div class="text-center">
    <h1>New Product</h1> 
  </div>
  <br />
  <%= render partial: "shared/product" %>
</div>

app/views/shared/_product.html.erb
<%= form_for @product do |f| %>
  <%= f.text_field :name, class: "form-control", placeholder: "Enter Product Name" %><br />
  <%= f.text_field :price, class: "form-control", placeholder: "Enter Product Price" %><br />
  <%= image_tag @product.image_url, width: '300px' if @product.image? %>
  <%= f.file_field :image %><br /><br />

  <%= f.submit 'Submit', class: "btn btn-outline-secondary"%>
<% end %>